<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    <RootNamespace>Tairitsua.Monica.GachaPool.Bridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tairitsua.Monica.GachaPool/Tairitsua.Monica.GachaPool.csproj" />
  </ItemGroup>
</Project>
